name: money_transfer_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  dotted_line: ^2.0.1
  firebase_core: ^0.5.0
  fluro: ^1.6.3
  flutter_masked_text: ^0.8.0
  flutter_screenutil: ^2.3.1
  flutter_svg: ^0.19.0
  flutter_staggered_animations: ^0.1.2
  fluttertoast: ^7.1.0
  fl_chart: ^0.12.0
  font_awesome_flutter: ^8.8.1
  image_picker: ^0.6.7+11
  intl_phone_number_input: ^0.4.6+2
  mask_text_input_formatter: 1.0.7
  persistent_bottom_nav_bar: ^2.0.5
  photo_view: ^0.10.2
  provider: ^4.3.2+2
  flutter_spinkit: ^4.1.2+1
  rflutter_alert: ^1.1.0

  status_alert:
    path: ../money_transfer_framework/lib/Widgets/status_alert

  pin_code_fields:
    path: ../money_transfer_framework/lib/Widgets/pin_code_fields

  money_transfer_framework:
    path: ../money_transfer_framework

  keicy_card_detect_provider:
    git: https://github.com/FlutterDev6778/keicy_card_detect_provider.git

  keicy_inkwell:
    git: https://github.com/FlutterDev6778/keicy_inkwell.git

  keicy_progress_dialog:
    git: https://github.com/FlutterDev6778/keicy_progress_dialog.git

  keicy_text_form_field:
    git: https://github.com/FlutterDev6778/keicy_text_form_field.git

  keicy_raised_button:
    git: https://github.com/FlutterDev6778/keicy_raised_button.git

  keicy_dropdown_form_field:
    git: https://github.com/FlutterDev6778/keicy_dropdown_form_field.git

  keicy_cupertino_indicator:
    git: https://github.com/FlutterDev6778/keicy_cupertino_indicator.git

  keicy_network_image:
    git: https://github.com/FlutterDev6778/keicy_network_image.git

  keicy_avatar_image:
    git: https://github.com/FlutterDev6778/keicy_avatar_image.git

  keicy_stripe_payment:
    git: https://github.com/FlutterDev6778/keicy_stripe_payment.git

  keicy_fcm_for_mobile_7_0:
    git: https://github.com/FlutterDev6778/keicy_fcm_for_mobile_7_0.git

  keicy_navigator:
    git: https://github.com/FlutterDev6778/keicy_navigator.git


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/Assets/Images/
    - lib/Assets/Images/Cards/
    - lib/Assets/Fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Exo
      fonts:
        - asset: lib/Assets/Fonts/Exo-Regular.ttf

    - family: Exo-SemiBold
      fonts:
        - asset: lib/Assets/Fonts/Exo-SemiBold.ttf

    - family: Exo-Medium
      fonts:
        - asset: lib/Assets/Fonts/Exo-Medium.ttf

    - family: Exo-Bold
      fonts:
        - asset: lib/Assets/Fonts/Exo-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
